package yt.entity.tbl;
// Generated Jan 13, 2017 3:31:54 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Comparator;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PartnerCountry generated by hbm2java
 */
@Entity
@Table(name = "Country", schema = "dbo")
public class Country implements Serializable {

    @Id
    @Column(name = "CountryID", unique = true, nullable = false)
    private String countryID;

    @Column(name = "CountryISO")
    private String countryISO;

    @Column(name = "CountryName")
    private String countryName;

    @Column(name = "PhoneCode")
    private String phoneCode;

    public Country() {
    }

    public String getCountryID() {
        return countryID;
    }

    public void setCountryID(String countryID) {
        this.countryID = countryID;
    }

    public String getCountryISO() {
        return countryISO;
    }

    public void setCountryISO(String countryISO) {
        this.countryISO = countryISO;
    }

    public String getCountryName() {
        return countryName;
    }

    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }

    public String getPhoneCode() {
        return phoneCode;
    }

    public void setPhoneCode(String phoneCode) {
        this.phoneCode = phoneCode;
    }

    /**
     * Sort by Alphabetically
     */
    public final static Comparator<Country> COUNTRY_NAME_COMPARATOR = (Country c1, Country c2) -> {
        String n1 = c1.getCountryName();
        String n2 = c2.getCountryName();
        return n1.compareTo(n2);
    };

}
