package yt.entity.tbl;
// Generated Jan 13, 2017 3:31:54 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
 * Partner generated by nick
 */
@Entity
@Table(name = "Partner", schema = "dbo")
public class Partner implements Serializable {

    @Id
    @Column(name = "PartnerID", unique = true, nullable = false)
    private String partnerID;

    @Column(name = "BusinessType")
    private String businessType;

    @Column(name = "BusinessName")
    private String businessName;

    @Column(name = "JobPosition")
    private String jobPosition;

    @Column(name = "DisplayName")
    private String displayName;

    @Column(name = "FirstName")
    private String firstName;

    @Column(name = "LastName")
    private String lastName;

    @Column(name = "CountryID")
    private String countryID;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "countryID", insertable = false, updatable = false)
    private PartnerCountry partnerCountry;

    @Column(name = "StateID")
    private Long stateID;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "stateID", insertable = false, updatable = false)
    private PartnerState partnerState;

    @Column(name = "BusinessCity")
    private String businessCity;

    @Column(name = "PostalCode")
    private String postalCode;

    @Column(name = "BusinessAddress")
    private String businessAddress;

    @Column(name = "PhoneCode")
    private String phoneCode;

    @Column(name = "PhoneNumber")
    private String phoneNumber;

    @Column(name = "BusinessBackground")
    private String businessBackground;

    @Column(name = "Avatar")
    private String avatar;

    @Column(name = "SmallAvatar")
    private String smallAvatar;

    @Column(name = "Email", nullable = false)
    private String email;

    @Column(name = "Password", nullable = false)
    private String password;

    @Column(name = "ResetPasswordToken")
    private String resetPasswordToken;

    @Column(name = "RegistrationDateTime")
    private Long registrationDateTime;

    @Column(name = "RegistrationToken")
    private String registrationToken;

    @Column(name = "AccountType", nullable = false)
    private String accountType;

    @Column(name = "AccountStatus", nullable = false)
    private String accountStatus;

    @Column(name = "LastVisitTime")
    private Long lastVisitTime;

    @Column(name = "PartnerLevel")
    private Integer partnerLevel;

    @Column(name = "VerificationID")
    private String verificationID;

    @Column(name = "VerficationStatus", nullable = false)
    private String verficationStatus;

    @Column(name = "VerificationFailReason")
    private String verificationFailReason;

    @Column(name = "BankID")
    private String bankID;

    @Column(name = "BankAccountName")
    private String bankAccountName;

    @Column(name = "BankAccountNumber")
    private String bankAccountNumber;

    @Column(name = "BankAccountStatus", nullable = false)
    private String bankAccountStatus;

    @Column(name = "BankFailReason")
    private String bankFailReason;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "partner")
    @Cascade(value = CascadeType.ALL)
    @LazyCollection(LazyCollectionOption.EXTRA)
    private Set<PartnerPersonalFile> personalFiles;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "partner")
    @Cascade(value = CascadeType.ALL)
    @LazyCollection(LazyCollectionOption.EXTRA)
    private Set<PartnerBankFile> bankFiles;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "partner")
    @Cascade(value = CascadeType.ALL)
    @LazyCollection(LazyCollectionOption.EXTRA)
    private Set<PartnerCertificate> certificates;

    public Partner() {
    }

    public String getPartnerID() {
        return partnerID;
    }

    public void setPartnerID(String partnerID) {
        this.partnerID = partnerID;
    }

    public String getBusinessType() {
        return businessType;
    }

    public void setBusinessType(String businessType) {
        this.businessType = businessType;
    }

    public String getBusinessName() {
        return businessName;
    }

    public void setBusinessName(String businessName) {
        this.businessName = businessName;
    }

    public String getJobPosition() {
        return jobPosition;
    }

    public void setJobPosition(String jobPosition) {
        this.jobPosition = jobPosition;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getCountryID() {
        return countryID;
    }

    public void setCountryID(String countryID) {
        this.countryID = countryID;
    }

    public PartnerCountry getPartnerCountry() {
        return partnerCountry;
    }

    public void setPartnerCountry(PartnerCountry partnerCountry) {
        this.partnerCountry = partnerCountry;
    }

    public Long getStateID() {
        return stateID;
    }

    public void setStateID(Long stateID) {
        this.stateID = stateID;
    }

    public PartnerState getPartnerState() {
        return partnerState;
    }

    public void setPartnerState(PartnerState partnerState) {
        this.partnerState = partnerState;
    }

    public String getBusinessCity() {
        return businessCity;
    }

    public void setBusinessCity(String businessCity) {
        this.businessCity = businessCity;
    }

    public String getPostalCode() {
        return postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    public String getBusinessAddress() {
        return businessAddress;
    }

    public void setBusinessAddress(String businessAddress) {
        this.businessAddress = businessAddress;
    }

    public String getPhoneCode() {
        return phoneCode;
    }

    public void setPhoneCode(String phoneCode) {
        this.phoneCode = phoneCode;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getBusinessBackground() {
        return businessBackground;
    }

    public void setBusinessBackground(String businessBackground) {
        this.businessBackground = businessBackground;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getSmallAvatar() {
        return smallAvatar;
    }

    public void setSmallAvatar(String smallAvatar) {
        this.smallAvatar = smallAvatar;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getResetPasswordToken() {
        return resetPasswordToken;
    }

    public void setResetPasswordToken(String resetPasswordToken) {
        this.resetPasswordToken = resetPasswordToken;
    }

    public Long getRegistrationDateTime() {
        return registrationDateTime;
    }

    public void setRegistrationDateTime(Long registrationDateTime) {
        this.registrationDateTime = registrationDateTime;
    }

    public String getRegistrationToken() {
        return registrationToken;
    }

    public void setRegistrationToken(String registrationToken) {
        this.registrationToken = registrationToken;
    }

    public String getAccountType() {
        return accountType;
    }

    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }

    public String getAccountStatus() {
        return accountStatus;
    }

    public void setAccountStatus(String accountStatus) {
        this.accountStatus = accountStatus;
    }

    public Long getLastVisitTime() {
        return lastVisitTime;
    }

    public void setLastVisitTime(Long lastVisitTime) {
        this.lastVisitTime = lastVisitTime;
    }

    public Integer getPartnerLevel() {
        return partnerLevel;
    }

    public void setPartnerLevel(Integer partnerLevel) {
        this.partnerLevel = partnerLevel;
    }

    public String getVerificationID() {
        return verificationID;
    }

    public void setVerificationID(String verificationID) {
        this.verificationID = verificationID;
    }

    public String getVerficationStatus() {
        return verficationStatus;
    }

    public void setVerficationStatus(String verficationStatus) {
        this.verficationStatus = verficationStatus;
    }

    public String getVerificationFailReason() {
        return verificationFailReason;
    }

    public void setVerificationFailReason(String verificationFailReason) {
        this.verificationFailReason = verificationFailReason;
    }

    public String getBankID() {
        return bankID;
    }

    public void setBankID(String bankID) {
        this.bankID = bankID;
    }

    public String getBankAccountName() {
        return bankAccountName;
    }

    public void setBankAccountName(String bankAccountName) {
        this.bankAccountName = bankAccountName;
    }

    public String getBankAccountNumber() {
        return bankAccountNumber;
    }

    public void setBankAccountNumber(String bankAccountNumber) {
        this.bankAccountNumber = bankAccountNumber;
    }

    public String getBankAccountStatus() {
        return bankAccountStatus;
    }

    public void setBankAccountStatus(String bankAccountStatus) {
        this.bankAccountStatus = bankAccountStatus;
    }

    public String getBankFailReason() {
        return bankFailReason;
    }

    public void setBankFailReason(String bankFailReason) {
        this.bankFailReason = bankFailReason;
    }

    public Set<PartnerPersonalFile> getPersonalFiles() {
        return personalFiles;
    }

    public void setPersonalFiles(Set<PartnerPersonalFile> personalFiles) {
        this.personalFiles = personalFiles;
    }

    public Set<PartnerBankFile> getBankFiles() {
        return bankFiles;
    }

    public void setBankFiles(Set<PartnerBankFile> bankFiles) {
        this.bankFiles = bankFiles;
    }

    public Set<PartnerCertificate> getCertificates() {
        return certificates;
    }

    public void setCertificates(Set<PartnerCertificate> certificates) {
        this.certificates = certificates;
    }

}
