package yt.entity.tbl;
// Generated Jan 13, 2017 3:31:54 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Partner generated by nick
 */
@Entity
@Table(name = "Tripper", schema = "dbo")
public class Tripper implements Serializable {

    @Id
    @Column(name = "TripperID", unique = true, nullable = false)
    private String tripperID;

    @Column(name = "FirstName")
    private String firstName;

    @Column(name = "LastName")
    private String lastName;

    @Column(name = "Gender")
    private Boolean gender;

    @Column(name = "DisplayName")
    private String displayName;

    @Column(name = "CountryID")
    private String countryID;

    @ManyToOne
    @JoinColumn(name = "CountryID", insertable = false, updatable = false)
    private Country country;

    @Column(name = "StateID")
    private Long stateID;

    @ManyToOne
    @JoinColumn(name = "StateID", insertable = false, updatable = false)
    private State state;

    @Column(name = "PersonalCity")
    private String personalCity;

    @Column(name = "PostalCode")
    private String postalCode;

    @Column(name = "PersonalAddress")
    private String personalAddress;

    @Column(name = "PhoneCode")
    private String phoneCode;

    @Column(name = "PhoneNumber")
    private String phoneNumber;

    @Column(name = "Company")
    private String company;

    @Column(name = "TaxNumber")
    private String taxNumber;

    @Column(name = "PreferedLanguageID")
    private String preferedLanguageID;

    @Column(name = "Background")
    private String background;

    @Column(name = "Avatar")
    private String avatar;

    @Column(name = "SmallAvatar")
    private String smallAvatar;

    @Column(name = "Email")
    private String email;

    @Column(name = "Password", nullable = false)
    private String password;

    @Column(name = "ResetPasswordToken")
    private String resetPasswordToken;

    @Column(name = "RegistrationDateTime")
    private Long registrationDateTime;

    @Column(name = "RegistrationToken")
    private String registrationToken;

    @Column(name = "AccountType", nullable = false)
    private String accountType;

    @Column(name = "AccountStatus", nullable = false)
    private String accountStatus;

    @Column(name = "FacebookID")
    private String facebookID;

    @Column(name = "GoogleID")
    private String googleID;

    @Column(name = "LineID")
    private String lineID;

    @Column(name = "LastVisitTime")
    private Long lastVisitTime;

    public Tripper() {
    }

    public String getTripperID() {
        return tripperID;
    }

    public void setTripperID(String tripperID) {
        this.tripperID = tripperID;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Boolean getGender() {
        return gender;
    }

    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getCountryID() {
        return countryID;
    }

    public void setCountryID(String countryID) {
        this.countryID = countryID;
    }

    public Country getCountry() {
        return country;
    }

    public void setCountry(Country country) {
        this.country = country;
    }

    public Long getStateID() {
        return stateID;
    }

    public void setStateID(Long stateID) {
        this.stateID = stateID;
    }

    public State getState() {
        return state;
    }

    public void setState(State state) {
        this.state = state;
    }

    public String getPersonalCity() {
        return personalCity;
    }

    public void setPersonalCity(String personalCity) {
        this.personalCity = personalCity;
    }

    public String getPostalCode() {
        return postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    public String getPersonalAddress() {
        return personalAddress;
    }

    public void setPersonalAddress(String personalAddress) {
        this.personalAddress = personalAddress;
    }

    public String getPhoneCode() {
        return phoneCode;
    }

    public void setPhoneCode(String phoneCode) {
        this.phoneCode = phoneCode;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public String getTaxNumber() {
        return taxNumber;
    }

    public void setTaxNumber(String taxNumber) {
        this.taxNumber = taxNumber;
    }

    public String getPreferedLanguageID() {
        return preferedLanguageID;
    }

    public void setPreferedLanguageID(String preferedLanguageID) {
        this.preferedLanguageID = preferedLanguageID;
    }

    public String getBackground() {
        return background;
    }

    public void setBackground(String background) {
        this.background = background;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getSmallAvatar() {
        return smallAvatar;
    }

    public void setSmallAvatar(String smallAvatar) {
        this.smallAvatar = smallAvatar;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getResetPasswordToken() {
        return resetPasswordToken;
    }

    public void setResetPasswordToken(String resetPasswordToken) {
        this.resetPasswordToken = resetPasswordToken;
    }

    public Long getRegistrationDateTime() {
        return registrationDateTime;
    }

    public void setRegistrationDateTime(Long registrationDateTime) {
        this.registrationDateTime = registrationDateTime;
    }

    public String getRegistrationToken() {
        return registrationToken;
    }

    public void setRegistrationToken(String registrationToken) {
        this.registrationToken = registrationToken;
    }

    public String getAccountType() {
        return accountType;
    }

    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }

    public String getAccountStatus() {
        return accountStatus;
    }

    public void setAccountStatus(String accountStatus) {
        this.accountStatus = accountStatus;
    }

    public String getFacebookID() {
        return facebookID;
    }

    public void setFacebookID(String facebookID) {
        this.facebookID = facebookID;
    }

    public String getGoogleID() {
        return googleID;
    }

    public void setGoogleID(String googleID) {
        this.googleID = googleID;
    }

    public String getLineID() {
        return lineID;
    }

    public void setLineID(String lineID) {
        this.lineID = lineID;
    }

    public Long getLastVisitTime() {
        return lastVisitTime;
    }

    public void setLastVisitTime(Long lastVisitTime) {
        this.lastVisitTime = lastVisitTime;
    }

}
