package yt.entity.tbl;
// Generated Jan 13, 2017 3:31:54 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Bucket generated by hbm2java
 */
@Entity
@Table(name = "TripperWishlist", schema = "dbo")
public class TripperWishlist implements Serializable {

    @Id
    @Column(name = "PackageID")
    private String packageID;

    @Id
    @Column(name = "TripperID")
    private String tripperID;

    @Column(name = "WishlistDateTime")
    private long wishlistDateTime;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PackageID", insertable = false, updatable = false)
    private YTPackage ytPackage;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TripperID", insertable = false, updatable = false)
    private Tripper tripper;

    public TripperWishlist() {
    }

    public String getPackageID() {
        return packageID;
    }

    public void setPackageID(String packageID) {
        this.packageID = packageID;
    }

    public String getTripperID() {
        return tripperID;
    }

    public void setTripperID(String tripperID) {
        this.tripperID = tripperID;
    }

    public long getWishlistDateTime() {
        return wishlistDateTime;
    }

    public void setWishlistDateTime(long wishlistDateTime) {
        this.wishlistDateTime = wishlistDateTime;
    }

    public YTPackage getYtPackage() {
        return ytPackage;
    }

    public void setYtPackage(YTPackage ytPackage) {
        this.ytPackage = ytPackage;
    }

    public Tripper getTripper() {
        return tripper;
    }

    public void setTripper(Tripper tripper) {
        this.tripper = tripper;
    }

}
