package yt.entity.tbl;
// Generated Jan 13, 2017 3:31:54 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Partner generated by nick
 */
@Entity
@Table(name = "YTBookingOrder", schema = "dbo")
public class YTBookingOrder implements Serializable {

    @Id
    @Column(name = "OrderNo", unique = true, nullable = false)
    private String orderNo;

    @Column(name = "TransactionID")
    private String transactionID;

    @Column(name = "TripperID")
    private String tripperID;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tripperID", insertable = false, updatable = false)
    private Tripper tripper;

    @Column(name = "TripperEmail")
    private String tripperEmail;

    @Column(name = "BillingFirstName")
    private String billingFirstName;

    @Column(name = "BillingLastName")
    private String billingLastName;

    @Column(name = "PackageID")
    private String packageID;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PackageID", insertable = false, updatable = false)
    private YTPackage ytPackage;

    @Column(name = "ServingType")
    private String servingType;

    @Column(name = "BookingDate")
    private long bookingDate;

    @Column(name = "BookingDateTime")
    private long bookingDateTime;

    @Column(name = "CurrencyCode")
    private String currencyCode;

    @Column(name = "Total")
    private BigDecimal total;

    @Column(name = "DiscountCode")
    private String discountCode;

    @Column(name = "TotalDiscount")
    private BigDecimal totalDiscount;

    @Column(name = "FinalTotal")
    private BigDecimal finalTotal;

    @Column(name = "ExchangeRate")
    private BigDecimal exchangeRate;

    @Column(name = "PaymentRate")
    private BigDecimal paymentRate;

    @Column(name = "FinalRate")
    private BigDecimal finalRate;

    @Column(name = "Amount")
    private BigDecimal amount;

    @Column(name = "CommissionRate")
    private BigDecimal commissionRate;

    @Column(name = "YTCommission")
    private BigDecimal ytCommission;

    @Column(name = "PartnerPayable")
    private BigDecimal partnerPayable;

    @Column(name = "PackageName")
    private String packageName;

    @Column(name = "PackagePrice")
    private BigDecimal packagePrice;

    @Column(name = "PaymentPrice")
    private BigDecimal paymentPrice;

    @Column(name = "OnPromotional")
    private boolean onPromotional;

    @Column(name = "TripDate")
    private Long tripDate;

    @Column(name = "TripTime")
    private Integer tripTime;

    @Column(name = "DurationType")
    private String durationType;

    @Column(name = "BusinessDuration")
    private Integer businessDuration;

    @Column(name = "ExpirationDate")
    private Long expirationDate;

    @Column(name = "OTServingQTY")
    private Integer otServingQTY;

    @Column(name = "OTServedQTY")
    private int otServedQTY;

    @Column(name = "QuotaDate")
    private Long quotaDate;

    @Column(name = "QuotaTime")
    private Integer quotaTime;

    @Column(name = "UsedQuota")
    private int usedQuota;

    @Column(name = "OfflineBooking")
    private boolean offlineBooking;

    @Column(name = "PaymentStatus")
    private String paymentStatus;

    @Column(name = "PaymentMethod")
    private String paymentMethod;

    @Column(name = "PaypalID")
    private String paypalID;

    @Column(name = "LinepayID")
    private String linepayID;

    @Column(name = "CreditCardID")
    private Long creditCardID;

    @Column(name = "VisaMasterCardNo")
    private String visaMasterCardNo;

    @Column(name = "VisaMasterHolderName")
    private String visaMasterHolderName;

    @Column(name = "VisaMasterCardExMonth")
    private Integer visaMasterCardExMonth;

    @Column(name = "VisaMasterCardExYear")
    private Integer visaMasterCardExYear;

    @Column(name = "VisaMasterCardType")
    private String visaMasterCardType;

    @Column(name = "TripperAbsence")
    private Boolean tripperAbsence;

    @Column(name = "OTExpired")
    private boolean otExpired;

    @Column(name = "OTExpiredDate")
    private Long otExpiredDate;

    @Column(name = "RPServed")
    private boolean rpServed;

    @Column(name = "ReviewToken")
    private String reviewToken;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ReviewToken", insertable = false, updatable = false)
    private YTPackageReview ytPackageReview;

    @Column(name = "PayableBill")
    private boolean payableBill;

    @Column(name = "PayableBillDate")
    private Long payableBillDate;

    @Column(name = "WithdrawStatus")
    private String withdrawStatus;

    @Column(name = "WithdrawDate")
    private Long withdrawDate;

    @Column(name = "InvoiceContent")
    private String invoiceContent;

    @Column(name = "InvoiceName")
    private String invoiceName;

    @Column(name = "InvoiceFile")
    private String invoiceFile;

    @Column(name = "CompletedPayment")
    private boolean completedPayment;

    public YTBookingOrder() {
    }

    public String getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    public String getTransactionID() {
        return transactionID;
    }

    public void setTransactionID(String transactionID) {
        this.transactionID = transactionID;
    }

    public String getTripperID() {
        return tripperID;
    }

    public void setTripperID(String tripperID) {
        this.tripperID = tripperID;
    }

    public Tripper getTripper() {
        return tripper;
    }

    public void setTripper(Tripper tripper) {
        this.tripper = tripper;
    }

    public String getTripperEmail() {
        return tripperEmail;
    }

    public void setTripperEmail(String tripperEmail) {
        this.tripperEmail = tripperEmail;
    }

    public String getBillingFirstName() {
        return billingFirstName;
    }

    public void setBillingFirstName(String billingFirstName) {
        this.billingFirstName = billingFirstName;
    }

    public String getBillingLastName() {
        return billingLastName;
    }

    public void setBillingLastName(String billingLastName) {
        this.billingLastName = billingLastName;
    }

    public String getPackageID() {
        return packageID;
    }

    public void setPackageID(String packageID) {
        this.packageID = packageID;
    }

    public YTPackage getYtPackage() {
        return ytPackage;
    }

    public void setYtPackage(YTPackage ytPackage) {
        this.ytPackage = ytPackage;
    }

    public String getServingType() {
        return servingType;
    }

    public void setServingType(String servingType) {
        this.servingType = servingType;
    }

    public long getBookingDate() {
        return bookingDate;
    }

    public void setBookingDate(long bookingDate) {
        this.bookingDate = bookingDate;
    }

    public long getBookingDateTime() {
        return bookingDateTime;
    }

    public void setBookingDateTime(long bookingDateTime) {
        this.bookingDateTime = bookingDateTime;
    }

    public String getCurrencyCode() {
        return currencyCode;
    }

    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    public BigDecimal getTotal() {
        return total;
    }

    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    public String getDiscountCode() {
        return discountCode;
    }

    public void setDiscountCode(String discountCode) {
        this.discountCode = discountCode;
    }

    public BigDecimal getTotalDiscount() {
        return totalDiscount;
    }

    public void setTotalDiscount(BigDecimal totalDiscount) {
        this.totalDiscount = totalDiscount;
    }

    public BigDecimal getFinalTotal() {
        return finalTotal;
    }

    public void setFinalTotal(BigDecimal finalTotal) {
        this.finalTotal = finalTotal;
    }

    public BigDecimal getExchangeRate() {
        return exchangeRate;
    }

    public void setExchangeRate(BigDecimal exchangeRate) {
        this.exchangeRate = exchangeRate;
    }

    public BigDecimal getPaymentRate() {
        return paymentRate;
    }

    public void setPaymentRate(BigDecimal paymentRate) {
        this.paymentRate = paymentRate;
    }

    public BigDecimal getFinalRate() {
        return finalRate;
    }

    public void setFinalRate(BigDecimal finalRate) {
        this.finalRate = finalRate;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public BigDecimal getCommissionRate() {
        return commissionRate;
    }

    public void setCommissionRate(BigDecimal commissionRate) {
        this.commissionRate = commissionRate;
    }

    public BigDecimal getYtCommission() {
        return ytCommission;
    }

    public void setYtCommission(BigDecimal ytCommission) {
        this.ytCommission = ytCommission;
    }

    public BigDecimal getPartnerPayable() {
        return partnerPayable;
    }

    public void setPartnerPayable(BigDecimal partnerPayable) {
        this.partnerPayable = partnerPayable;
    }

    public String getPackageName() {
        return packageName;
    }

    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    public BigDecimal getPackagePrice() {
        return packagePrice;
    }

    public void setPackagePrice(BigDecimal packagePrice) {
        this.packagePrice = packagePrice;
    }

    public BigDecimal getPaymentPrice() {
        return paymentPrice;
    }

    public void setPaymentPrice(BigDecimal paymentPrice) {
        this.paymentPrice = paymentPrice;
    }

    public boolean isOnPromotional() {
        return onPromotional;
    }

    public void setOnPromotional(boolean onPromotional) {
        this.onPromotional = onPromotional;
    }

    public Long getTripDate() {
        return tripDate;
    }

    public void setTripDate(Long tripDate) {
        this.tripDate = tripDate;
    }

    public Integer getTripTime() {
        return tripTime;
    }

    public void setTripTime(Integer tripTime) {
        this.tripTime = tripTime;
    }

    public String getDurationType() {
        return durationType;
    }

    public void setDurationType(String durationType) {
        this.durationType = durationType;
    }

    public Integer getBusinessDuration() {
        return businessDuration;
    }

    public void setBusinessDuration(Integer businessDuration) {
        this.businessDuration = businessDuration;
    }

    public Long getExpirationDate() {
        return expirationDate;
    }

    public void setExpirationDate(Long expirationDate) {
        this.expirationDate = expirationDate;
    }

    public Integer getOtServingQTY() {
        return otServingQTY;
    }

    public void setOtServingQTY(Integer otServingQTY) {
        this.otServingQTY = otServingQTY;
    }

    public int getOtServedQTY() {
        return otServedQTY;
    }

    public void setOtServedQTY(int otServedQTY) {
        this.otServedQTY = otServedQTY;
    }

    public Long getQuotaDate() {
        return quotaDate;
    }

    public void setQuotaDate(Long quotaDate) {
        this.quotaDate = quotaDate;
    }

    public Integer getQuotaTime() {
        return quotaTime;
    }

    public void setQuotaTime(Integer quotaTime) {
        this.quotaTime = quotaTime;
    }

    public int getUsedQuota() {
        return usedQuota;
    }

    public void setUsedQuota(int usedQuota) {
        this.usedQuota = usedQuota;
    }

    public boolean isOfflineBooking() {
        return offlineBooking;
    }

    public void setOfflineBooking(boolean offlineBooking) {
        this.offlineBooking = offlineBooking;
    }

    public String getPaymentStatus() {
        return paymentStatus;
    }

    public void setPaymentStatus(String paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    public String getPaymentMethod() {
        return paymentMethod;
    }

    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    public String getPaypalID() {
        return paypalID;
    }

    public void setPaypalID(String paypalID) {
        this.paypalID = paypalID;
    }

    public String getLinepayID() {
        return linepayID;
    }

    public void setLinepayID(String linepayID) {
        this.linepayID = linepayID;
    }

    public Long getCreditCardID() {
        return creditCardID;
    }

    public void setCreditCardID(Long creditCardID) {
        this.creditCardID = creditCardID;
    }

    public String getVisaMasterCardNo() {
        return visaMasterCardNo;
    }

    public void setVisaMasterCardNo(String visaMasterCardNo) {
        this.visaMasterCardNo = visaMasterCardNo;
    }

    public String getVisaMasterHolderName() {
        return visaMasterHolderName;
    }

    public void setVisaMasterHolderName(String visaMasterHolderName) {
        this.visaMasterHolderName = visaMasterHolderName;
    }

    public Integer getVisaMasterCardExMonth() {
        return visaMasterCardExMonth;
    }

    public void setVisaMasterCardExMonth(Integer visaMasterCardExMonth) {
        this.visaMasterCardExMonth = visaMasterCardExMonth;
    }

    public Integer getVisaMasterCardExYear() {
        return visaMasterCardExYear;
    }

    public void setVisaMasterCardExYear(Integer visaMasterCardExYear) {
        this.visaMasterCardExYear = visaMasterCardExYear;
    }

    public String getVisaMasterCardType() {
        return visaMasterCardType;
    }

    public void setVisaMasterCardType(String visaMasterCardType) {
        this.visaMasterCardType = visaMasterCardType;
    }

    public Boolean getTripperAbsence() {
        return tripperAbsence;
    }

    public void setTripperAbsence(Boolean tripperAbsence) {
        this.tripperAbsence = tripperAbsence;
    }

    public boolean isOtExpired() {
        return otExpired;
    }

    public void setOtExpired(boolean otExpired) {
        this.otExpired = otExpired;
    }

    public Long getOtExpiredDate() {
        return otExpiredDate;
    }

    public void setOtExpiredDate(Long otExpiredDate) {
        this.otExpiredDate = otExpiredDate;
    }

    public boolean isRpServed() {
        return rpServed;
    }

    public void setRpServed(boolean rpServed) {
        this.rpServed = rpServed;
    }

    public String getReviewToken() {
        return reviewToken;
    }

    public void setReviewToken(String reviewToken) {
        this.reviewToken = reviewToken;
    }

    public YTPackageReview getYtPackageReview() {
        return ytPackageReview;
    }

    public void setYtPackageReview(YTPackageReview ytPackageReview) {
        this.ytPackageReview = ytPackageReview;
    }

    public boolean isPayableBill() {
        return payableBill;
    }

    public void setPayableBill(boolean payableBill) {
        this.payableBill = payableBill;
    }

    public Long getPayableBillDate() {
        return payableBillDate;
    }

    public void setPayableBillDate(Long payableBillDate) {
        this.payableBillDate = payableBillDate;
    }

    public String getWithdrawStatus() {
        return withdrawStatus;
    }

    public void setWithdrawStatus(String withdrawStatus) {
        this.withdrawStatus = withdrawStatus;
    }

    public Long getWithdrawDate() {
        return withdrawDate;
    }

    public void setWithdrawDate(Long withdrawDate) {
        this.withdrawDate = withdrawDate;
    }

    public String getInvoiceContent() {
        return invoiceContent;
    }

    public void setInvoiceContent(String invoiceContent) {
        this.invoiceContent = invoiceContent;
    }

    public String getInvoiceName() {
        return invoiceName;
    }

    public void setInvoiceName(String invoiceName) {
        this.invoiceName = invoiceName;
    }

    public String getInvoiceFile() {
        return invoiceFile;
    }

    public void setInvoiceFile(String invoiceFile) {
        this.invoiceFile = invoiceFile;
    }

    public boolean isCompletedPayment() {
        return completedPayment;
    }

    public void setCompletedPayment(boolean completedPayment) {
        this.completedPayment = completedPayment;
    }

}
